### ISSUE TITLE
linux desteği var mı?

### ISSUE THREAD

**Issue by kadirnar** [MehmetOKUYAR/Auto_video_label#1]
Merhaba Mehmet,

Auto_video_label kütüphanesini windows da denedim başarılı bir şekilde çalışıyor. Fakat ubuntu da denediğimde şu hatayı veriyor:

```
QObject::moveToThread: Current thread (0x29e4280) is not the object's thread (0x2b75050).
Cannot move to target thread (0x29e4280)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/kadir/virtualenvironment/torchyolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
```

Ubuntu da desteği var mı? Yoksa benim kütüphanelerle mi ilgili?

**Comment by MehmetOKUYAR** [comment]
Merhaba Kadir, 
ubuntu işletim sisteminde pyqt den dolayı bir başka bir hata alıyorum bende ama şimdi kodlarda güncelleme yaptım. Arayüz olmadan ubuntu da kullanabilmen için yeni bir kod yükledim. Onu deneyebilirsen sevinirim.

**Comment by kadirnar** [comment]
Maalesef bende çalışmadı. Aynı şekilde hata basıyor.

```
QObject::moveToThread: Current thread (0x1866280) is not the object's thread (0x1de3970).
Cannot move to target thread (0x1866280)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/kadir/virtualenvironment/torchyolo/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by MehmetOKUYAR** [comment]
bu arayüz için verdiği bir hata pyqt den kaynaklı 

### For ubuntu 

**requirements --> opencv-contrib-python==4.2.0.34**

**You should run it like this** `python3 auto_label.py --video video.mp4 --className label --perFrame 1 --classId 0`

arayüz olmadan bu şekilde test ettiğimde ben bir problem almıyorum.

**Comment by kadirnar** [comment]
Başarılı şekilde çalışıyor. Eline sağlık. Etiket için .txt dışında .json desteği de gelirse çok daha verimli olacaktır👍

**Comment by MehmetOKUYAR** [comment]
geri dönütlerin için teşekkürler. müsait bir zamanda ilgileneceğim ekstra diğer formatlarda da kayıt etme seçeneği de eklemeyi düşünüyorum.
