### ISSUE TITLE
Desteklenmeyen opencv sürümü

### ISSUE THREAD

**Issue by kadirnar** [MehmetOKUYAR/Auto_video_label#2]
Windows da git clone yaparak test ettiğimizde 4.2.0.34 sürümü windows da yok. 4.4.0.46 veya 3.4.17.61 sürümünü test ettiğimizde hata veriyor. Windows da kullandığın opencv sürümün nedir?

**Comment by MehmetOKUYAR** [comment]
windows da opencv==4.4.0  versiyonunu kullanıyorum herhangi bir hata ile karşılaşmadım. Sorunu çözebildiniz mi ?
